[ircServer]
ircServerHost = "irc.rizon.net"
ircServerPort = 7000
ircServerPass = ""

[ircClient]
ircBotUser = "pybot"
ircBotNick = "PyBot"
ircBotRnam = "Python IRC Bot"
ircBotNspw = ""
ircBotAcon = true
ircBotCsym = "!"
ircBotRcon = ""
ircBotDccv = "VERSION PyIRC Bot"
ircBotChan = [ "#test", "#rand",]
ircBotAdmi = [ "BotMaster1", "admi",]
